### ISSUE TITLE
Impressive works, and i wonder to know when to open.

### ISSUE THREAD

**Issue by npujcong** [yl4579/StyleTTS#1]

**Comment by yl4579** [comment]
I will upload the code by this month. Sorry for the long wait.

**Comment by RFTuna** [comment]
this month as in the end of November? any update on this?

**Comment by yl4579** [comment]
@RFTuna Sorry, I meant the end of December, being very busy with my schoolwork. I will make sure to push it by the holiday.

**Comment by yl4579** [comment]
I have made the preliminary training code available, but it may have some bugs. I'm working on the LibriTTS models now and will make them available ASAP. After that, I will try to train an LJSpeech model using the preprocessing of official HifiGAN.
