### ISSUE TITLE
Process for setting up other datasets

### ISSUE THREAD

**Issue by crypticsymmetry** [yl4579/StyleTTS#12]
Hello there! new to this speech synthesis stuff, whats the process for setting up a dataset like the VCTK dataset (downsampled to 24khz) and processing it in the proper format like in the example for LibriTTS "filename.wav|transcription". 
"LibriTTS/train-clean-460/7169/89735/7169_89735_000071_000003.wav|wˈʌn mˌeɪd ˌʌp wˈʌnz mˈaɪnd ðə lˈoʊn wˈʊlf mˈʌst biː ɐ sˈɜːʔn̩ sˈɔːɹt ʌv mˈæn; ðə ɹˈɛst wʌz sˈɪmpli sˈɪftɪŋ fɹˈæns fɚðə mˈæn tə fˈɪt ðə θˈiəɹi, ænd ðˈɛn wˈɑːtʃɪŋ hˌɪm ʌntˈɪl hiː ɡˈeɪv hɪmsˈɛlf ɐwˈeɪ."
"
its not clear to me how i get the transciption from the text and set all of that up. If any one has set up a dataset like this one before and can help point me in the right direction that would be awesome! Thanks.

**Comment by yl4579** [comment]
You can refer to [Inference_LJSpeech.ipynb](https://github.com/yl4579/StyleTTS/blob/main/Demo/Inference_LJSpeech.ipynb) for text preprocessing. The basic procedure is: 
```python
# load phonemizer
import phonemizer
global_phonemizer = phonemizer.backend.EspeakBackend(language='en-us', preserve_punctuation=True,  with_stress=True)

def phonemize(global_phonemizer, text):
    return global_phonemizer.phonemize([text])[0]
```
