### ISSUE TITLE
Multilingual Training [Question]

### ISSUE THREAD

**Issue by lexkoro** [yl4579/StyleTTS#15]
Hello, would it generally be possible to train StyleTTS on a multilingual dataset, e.g. by additionally conditioning the text encoder with a language embedding?

**Comment by twerpyfie** [comment]
Yea, thats my question too.

**Comment by yl4579** [comment]
From my experience, StyleTTS can be trained on multilingual datasets, and you don't even need to provide language embeddings if you use IPAs.
