### ISSUE TITLE
train_second step not fix decoder? 

### ISSUE THREAD

**Issue by liuhuang31** [yl4579/StyleTTS#18]
[https://github.com/yl4579/StyleTTS/blob/main/train_second.py#L297](https://github.com/yl4579/StyleTTS/blob/main/train_second.py#L297)

the above line is not in with torch.no_grad(), is it a problem?

**Comment by yl4579** [comment]
No, because the parameters of decoder aren't updated. There is no call with `optimizer.step('decoder')`.
