### ISSUE TITLE
Multi language support

### ISSUE THREAD

**Issue by Chopin68** [yl4579/StyleTTS#2]
Great works! 
I found that when there are other language characters, the synthesizer will repeatedly read the language+letter,What should I pay attention to if I want to add other languages.

**Comment by yl4579** [comment]
Not sure what you mean by "repeated read the language + letter", can you give an example of this problem? For other languages, you can simply use phonemizer to first convert your transcription into IPA and train your model directly with IPA. The pretrained text aligner was trained on LibriTTS (English), AiShell (Mandarin Chinese), and JVS (Japanese). It should have covered a wide range of IPA found in many languages (for example, Spanish besides the trill) and can be readily used for fine-tuning in other languages as long as you use the same preprocessing as in the meldataset.py file. 

By the way, there was some mistake in the code I uploaded. It was an updated version, not the original implementation. This version is unstable in training and may produce worse results than the previous one. I will find my original implementation and fix it in the meanwhile.

**Comment by Chopin68** [comment]
![image](https://user-images.githubusercontent.com/75252160/212221056-13d574b4-cb58-4904-a0be-b0809df7dea2.png)
I noticed the language option problem of phonemizer. Let it "repeat read the language+letter",

Thank you very much for your reply. It really helps a lot. I will try to train models in other languages with the International Phonetic Alphabet, and look forward to the fix in the future

**Comment by yl4579** [comment]
Not sure if you have solved this problem. It just hits me that phonemizer didn't work for me for Japanese and Chinese. I have made a comment on this problem here: https://github.com/yl4579/StyleTTS/issues/10
