### ISSUE TITLE
Pause between sentences?

### ISSUE THREAD

**Issue by ziyaad30** [yl4579/StyleTTS#22]
As the title suggests, how would I add a pause in between multiple sentences, for example after a full stop?

**Comment by yl4579** [comment]
You can either make a special token to indicate the pause or use punctuation which should usually be where the pauses are, like a period (.) for example.

**Comment by ziyaad30** [comment]
I know that, but even no slight pauses when you have a sentence that has a comma. Or could it be that I have to train more? As I am using my own datasets.

**Comment by yl4579** [comment]
Did your sentences all end with a comma? Then it probably won't have any pause because it's the end of the sentence. The pause token must be aligned with a pause in your dataset.

**Comment by ziyaad30** [comment]
I saw later I had no full stops in the train lists. Can we have a StyleTTS with the accompanying Aux and Pitch

**Comment by yl4579** [comment]
Yes, I will do that for the StyleTTS 2 repo. This should be up around July or August, please keep an eye on it.
