### ISSUE TITLE
s2s loss become nan

### ISSUE THREAD

**Issue by startreker-shzy** [yl4579/StyleTTS#26]
Thanks for you work.  I tried to train stage1 with multi-chinese dataset，about 420+ hours.   The training process is normal until some step the s2s loss become nan，after that the parameters of text aligner is nan too.  
What can i do to avoid this problem?
I tried to give an epsilon to _s2s_pred and set the loss to 0，but the parameters is still nan.
![image](https://github.com/yl4579/StyleTTS/assets/78834873/b795a026-2870-44b9-9421-6748a85cf409)

**Comment by yl4579** [comment]
Did you turn on the CE loss on?

**Comment by startreker-shzy** [comment]
I will try it.   Thanks again.
