### ISSUE TITLE
Why I can't  use your  mel to train HiFi-Gan Vocoder ?

### ISSUE THREAD

**Issue by dy2009** [yl4579/StyleTTS#29]
Hello, Yinghao Aaron Li

I use mel from "torchaudio.transforms.MelSpectrogram" to test  your  pretained HiGi-Gan model, is ok.
but  I use the mel to finetune the your  pretained HiGi-Gan model, the syn wav is noise.

I use your vocoder.py ,  use  HiFi-Gan code in  https://github.com/jik876/hifi-gan, train  the model, syn  wav is also ok.

What's the difference, in  your training process ?  Are you  changed something ?

**Comment by yl4579** [comment]
Because the preprocessing is different, please refer to https://github.com/yl4579/StarGANv2-VC/issues/59#issuecomment-1222763012 for the preprocessing of this repo.
