### ISSUE TITLE
What's r1_reg loss?

### ISSUE THREAD

**Issue by splinter21** [yl4579/StyleTTS#33]
https://github.com/yl4579/StyleTTS/blob/main/train_second.py#L307
I didn't see the details about it in your paper.

**Comment by yl4579** [comment]
It was copied from https://github.com/yl4579/StarGANv2-VC, and it doesn't matter that much (useful for unstable GAN training for faster convergence, but in this case it is reconstruction so it doesn't really matter). You can safely remove it and it shouldn't cause too much quality degradation.
