### ISSUE TITLE
Code for Emotional Speech Synthesis

### ISSUE THREAD

**Issue by satani99** [yl4579/StyleTTS#40]
As shown in the demo: https://styletts.github.io/ 
Can someone provide the code for Emotional speech synthesis for prosody transfer?

**Comment by yl4579** [comment]
You just provide different reference audios and it will automatically be changed to the emotion of the reference audio (if it is seen during training). Also, there's no prosody transfer on the demo page. If you meant voice conversion, you could refer to the StyleTTS-VC project here: https://github.com/yl4579/StyleTTS-VC
