### ISSUE TITLE
Would you recommend changing the code in the inference notebook when running a PL-BERT finetuned model?

### ISSUE THREAD

**Issue by exllama-fan** [yl4579/StyleTTS#42]
https://github.com/yl4579/StyleTTS/blob/eac67158fd21578ea950ff4d6734bf6e6434b6b5/Demo/Inference_LJSpeech.ipynb#L326

**Comment by yl4579** [comment]
The changed notebook is provided in the zipped file in the PL-BERT repo: https://drive.google.com/file/d/18DU4JrW1rhySrIk-XSxZkXt2MuznxoM-/view?usp=sharing
