### ISSUE TITLE
asr phone dict different from this

### ISSUE THREAD

**Issue by hdmjdp** [yl4579/StyleTTS#44]
hi，
https://github.com/yl4579/StyleTTS/blob/eac67158fd21578ea950ff4d6734bf6e6434b6b5/meldataset.py#L28C5-L28C5

the pretrained ASR model use this ""AA0",10
"AA1",11
"AA2",12
"AE0",13
"AE1",14
"AE2",15
"AH0",16
"AH1",17
"AH2",18
"AO0",19
"AO1",20
"AO2",21
"AW0",22
"AW1",23",

Why？

**Comment by yl4579** [comment]
Because it is a different model The ASR repo was made for StarGANv2-VC initially, while StyleTTS uses a different set of phonemes (IPA). I haven't updated the ASR repo yet, I will do so after I finish cleaning up the StyleTTS 2 code.
