### ISSUE TITLE
Can you offer the loss log of style tts

### ISSUE THREAD

**Issue by hdmjdp** [yl4579/StyleTTS#45]
Thanks a lot

**Comment by yl4579** [comment]
Here's what I have for the LJSpeech model. I will try to find the one for LibriTTS if you need them.

First stage:
![Screenshot 2023-08-17 202201](https://github.com/yl4579/StyleTTS/assets/71044569/94c59617-6e9b-4d26-9c2c-32ea8486fd0f)

Second stage:
![Screenshot 2023-08-17 202524](https://github.com/yl4579/StyleTTS/assets/71044569/61541794-5d4d-472e-93a4-632c2ec8a714)

Note that for the second stage training was separated and the epochs were not connected for some reason, but in total it was trained for 100 epochs.
