### ISSUE TITLE
Source of Hifigan checkpoints?

### ISSUE THREAD

**Issue by kmn1024** [yl4579/StyleTTS#47]
Are the Hifigan checkpoints copied from somewhere? The paper is suggestive of https://github.com/kan-bayashi/ParallelWaveGAN, but https://drive.google.com/drive/folders/10jBLsjQT3LvR-3GgPZpRvWIWvpGjzDnM (the LibriTTS Hifigan checkpoint from https://github.com/kan-bayashi/ParallelWaveGAN#results) has 2500000 steps, as opposed to g_00935000 from the link under StyleTTS, so it doesn't match.

Did the authors pretrain Hifigan themselves from scratch?

**Comment by yl4579** [comment]
Which paper are you referring to? StyleTTS uses Hifi-GAN while StarGANv2-VC uses ParallelWaveGAN. I think you might have confused these two projects.
