### ISSUE TITLE
Finetuning on a small dataset?

### ISSUE THREAD

**Issue by godspirit00** [yl4579/StyleTTS#5]
Hi!
Thanks for the great work!
I trained a model on ryanspeech, and it sounds great!
I have a small dataset of around 2h, so is it possible to finetune an existing model on a small dataset?
Thanks!
And happy Chinese New Year!

**Comment by yl4579** [comment]
I haven't tried this yet, but my gut is that it's definitely possible, especially when your base model contains a lot of speakers. Let me know what you have found.
