### ISSUE TITLE
About train on Vietnamese Dataset

### ISSUE THREAD

**Issue by christopherohit** [yl4579/StyleTTS#52]
I really get into trouble when starting a project with a Vietnamese dataset, Can you describe in detail every task that I will do before starting with styleTTS and the format of data to train it to look like the [file in your folder data](https://github.com/yl4579/StyleTTS/blob/main/Data/train_list_libritts.txt)
Or like here?
![image](https://github.com/yl4579/StyleTTS/assets/55018999/6901485e-eaf3-46ab-b53d-4bf1e791072e)

I would really appreciate it if you could help me describe each step clearly

Thank you, Hope you have a good day

**Comment by yl4579** [comment]
Maybe you can refer to this https://github.com/yihuitang/StyleTTS_Mandarin? You just need to phonemize Vietnamese into IPAs and add the tones of each word.
