### ISSUE TITLE
多卡训练的问题

### ISSUE THREAD

**Issue by bobo-paopao** [yl4579/StyleTTS#53]
将config.yml文件中的multigpu: true设置为true，使用多卡进行模型的训练，训练完一代的时候在参数拼接的时候出现RuntimeError: Expected all input tensors to have the same number of dimensions, but tensor at index 2has 1 dimensions, (expected 2)，此问题应该怎么解决呢？

**Comment by yl4579** [comment]
Which line has caused this problem?

**Comment by yl4579** [comment]
Maybe can you make sure that the batch size is at least the number of GPUs you are using right now?

**Comment by bobo-paopao** [comment]
Yes, it was the batch_size inconsistency that was causing the problem, solved, thanks a lot!

**Comment by SoshyHayami** [comment]
i'm getting this error as well. works fine on single-gpu but in multiple gpu no matter what batch size i use, i get the same error (at index 1)
