### ISSUE TITLE
what is the mean=-4 and std=4 meannig?

### ISSUE THREAD

**Issue by skysbird** [yl4579/StyleTTS#57]
https://github.com/yl4579/StyleTTS/blame/eac67158fd21578ea950ff4d6734bf6e6434b6b5/meldataset.py#L62

i found that in styletts-vc project ,some times, this value leads to some high pitch loss? Can i adjust this value?

**Comment by yl4579** [comment]
Yes, it is an arbitrary number to prevent log melspectrogram from exploding. You can easily adjust these numbers to fit your dataset.
