### ISSUE TITLE
RuntimeError: espeak not installed on your system

### ISSUE THREAD

**Issue by HobisPL** [yl4579/StyleTTS#6]
I have installed Phonemizer, but I am receiving an error about missing espeak. I have also tried to download espeak from the website and added it to the environment variable, but I am still receiving this error. I am also receiving another error about unicode decode.

`---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_18492\1790917207.py in <module>
      1 # load phonemizer
      2 import phonemizer
----> 3 global_phonemizer = phonemizer.backend.EspeakBackend(language='en-us', preserve_punctuation=True,  with_stress=True)

~\anaconda3.1\lib\site-packages\phonemizer\backend\espeak\espeak.py in __init__(self, language, punctuation_marks, preserve_punctuation, with_stress, tie, language_switch, words_mismatch, logger)
     45         super().__init__(
     46             language, punctuation_marks=punctuation_marks,
---> 47             preserve_punctuation=preserve_punctuation, logger=logger)
     48 
     49         self._espeak.set_voice(language)

~\anaconda3.1\lib\site-packages\phonemizer\backend\espeak\base.py in __init__(self, language, punctuation_marks, preserve_punctuation, logger)
     41             punctuation_marks=punctuation_marks,
     42             preserve_punctuation=preserve_punctuation,
---> 43             logger=logger)
     44 
     45         self._espeak = EspeakWrapper()

~\anaconda3.1\lib\site-packages\phonemizer\backend\base.py in __init__(self, language, punctuation_marks, preserve_punctuation, logger)
     76         if not self.is_available():
     77             raise RuntimeError(  # pragma: nocover
---> 78                 '{} not installed on your system'.format(self.name()))
     79 
     80         self._logger = logger

RuntimeError: espeak not installed on your system`

`---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_15548\494391268.py in <module>
      3 train_path = config.get('train_data', None)
      4 val_path = config.get('val_data', None)
----> 5 train_list, val_list = get_data_path_list(train_path, val_path)
      6 
      7 ref_dicts = {}

~\Desktop\github\StyleTTS\utils.py in get_data_path_list(train_path, val_path)
     33 
     34     with open(train_path, 'r') as f:
---> 35         train_list = f.readlines()
     36     with open(val_path, 'r') as f:
     37         val_list = f.readlines()

~\anaconda3.1\lib\encodings\cp1250.py in decode(self, input, final)
     21 class IncrementalDecoder(codecs.IncrementalDecoder):
     22     def decode(self, input, final=False):
---> 23         return codecs.charmap_decode(input,self.errors,decoding_table)[0]
     24 
     25 class StreamWriter(Codec,codecs.StreamWriter):

UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 39: character maps to <undefined>`

**Comment by yl4579** [comment]
For the first problem, it's better to ask in the [phonemizer ](https://github.com/bootphon/phonemizer) repo. I'm not a developer of phonemzier or eSpeak, so I don't know what the problem is. 

For the second problem,  you will need to replace `with open(train_path, 'r') as f:` with `with open(train_path, 'r', encoding="utf8") as f:`. It seems like your system isn't UTF-8 for some reason.
