### ISSUE TITLE
What is the reason for multiply by 2 when stripping the batch

### ISSUE THREAD

**Issue by erogol** [yl4579/StyleTTS#8]
I could not find any mention in the paper. I wonder why the expanded text representation is half of the mel length as in the line below. Would you mind explaining the reason?

https://github.com/yl4579/StyleTTS/blob/451540dce1e52b5c5ecdc8fbea95af163e4b26e2/train_first.py#L327

**Comment by yl4579** [comment]
This is purely because the text aligner (ASR model) [here](https://github.com/yl4579/AuxiliaryASR) pools the mel dimension by two, so the alignment length is half of that of mel spectrogram.

**Comment by erogol** [comment]
thanks :)
